- name: Install nice to have packages
  hosts: adhoc
  gather_facts: true

  tasks:
    - name: Install extra packages
      become: true
      ansible.builtin.apt:
        pkg:
          - htop
          - jq
          - bat
          # - cpu-checker
          - magic-wormhole
          # - silversearcher-ag
          - tree
          - micro
        state: present
      when:
        - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Install extra packages
      become: true
      ansible.builtin.yum:
        name:
          - htop
          - jq
          - bat
          - cpu-checker
          - magic-wormhole
          - silversearcher-ag
          - tree
        state: present
      when:
        - ansible_distribution == "Amazon" or ansible_distribution == "CentOS"
