- name: Update packages via apt or yum depending on distro
  hosts: all
  become: true

  tasks:
    - name: Wait for sudo
      shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
      when:
        - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Update apt packages
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true
        cache_valid_time: 86400 # One day
      when:
        - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Update yum packages
      become_method: sudo
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: true
      when:
        - ansible_distribution == "Amazon"
