- name: Update packages via apt or yum depending on distro
  hosts: adhoc

  tasks:
    - name: Update apt packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
      when:
        - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Update yum packages
      become: true
      ansible.builtin.yum:
        update_cache: true
      when:
        - ansible_distribution == "Amazon" or ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "OracleLinux"