- name: Upgrade apt packages
  hosts: all

  tasks:
    - name: Upgrade apt packages
      become: true
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400 # One day
      when:
        - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
