- name: Install nice to have packages
  hosts: all
  gather_facts: true

  tasks:
    - name: Install with apt
      apt:
          - htop
          - jq
          - bat
          - magic-wormhole
          - silversearcher-ag
          - tree
          - micro
      state: present
      force_apt_get: yes
      when:
        - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

