- name: Update packages via apt or yum depending on distro
  hosts: all

  tasks:
    - name: Update apt packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Update yum packages
      become: true
      ansible.builtin.yum:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_distribution == "Amazon" or ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux"

    # - name: Send notification to Gotify
    #   ansible.builtin.shell: curl "https://push.example.de/message?token=<apptoken>" -F "title=my title" -F "message=my message" -F "priority=5"
    #   when: >
    #     '"Update apt packages" in ansible_run_tags' or '"Update yum packages" in ansible_run_tags'

    - name: Send notification to Gotify
      ansible.builtin.uri:
        url: "https://gotify.timmybtech.com/message?token=AoHTnmDZ1sx7Z4N"
        method: POST
        body_format: form-urlencoded
        body:
          title: "Ansible Update"
          message: "{{ ansible_distribution }} packages have been updated"
          priority: "5"
      when: >
        '"Update apt packages" in ansible_run_tags' or '"Update yum packages" in ansible_run_tags'
