- name: Update packages via apt or yum depending on distro
  hosts: all

  tasks:
    - name: Update apt packages
      become: true
      ansible.builtin.apt:
        update_cache: true
      when:
        - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Update yum packages
      become: true
      ansible.builtin.yum:
        update_cache: true
      when:
        - ansible_distribution == "Amazon"
